# Generated by Django 4.2.3 on 2024-10-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='file',
            field=models.FileField(upload_to='archiveapp/'),
        ),
    ]
