# Generated by Django 4.2.3 on 2024-10-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiveapp', '0002_alter_essay_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='file',
            field=models.FileField(upload_to='essays/'),
        ),
    ]
