# Generated by Django 4.2.3 on 2024-10-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiveapp', '0003_alter_category_name_alter_essay_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
